### ISSUE TITLE
error during build

### ISSUE THREAD

**Issue by alexschroeter** [jhnnsrs/konstruktor#1]
Trying to `yarn build` but I get the following error.

I created a new conda env and installed yarn with pip. Am I missing something?

```
$ tsc && vite build
error during build:
SyntaxError: Invalid regular expression: /(?<![\p{L}\p{N}_$]|(?<!\.\.)\.)(process\.env\.NODE_ENV|global\.process\.env\.NODE_ENV|globalThis\.process\.env\.NODE_ENV|__vite_process_env_NODE_ENV|import\.meta\.hot|import\.meta\.env\.BASE_URL|import\.meta\.env\.MODE|import\.meta\.env\.DEV|import\.meta\.env\.PROD|import\.meta\.env\.SSR|import\.meta\.env\.|import\.meta\.env|process\.env\.|global\.process\.env\.|globalThis\.process\.env\.)(?:(?<=\.)|(?![\p{L}\p{N}_$]|\s*?=[^=]))/: Invalid property name in character class
    at new RegExp (<anonymous>)
    at generatePattern (file:///mnt/c/Users/aschr/Documents/konstruktor/node_modules/vite/dist/node/chunks/dep-3007b26d.js:40424:15)
    at definePlugin (file:///mnt/c/Users/aschr/Documents/konstruktor/node_modules/vite/dist/node/chunks/dep-3007b26d.js:40439:28)
    at resolvePlugins (file:///mnt/c/Users/aschr/Documents/konstruktor/node_modules/vite/dist/node/chunks/dep-3007b26d.js:41066:9)
    at async resolveConfig (file:///mnt/c/Users/aschr/Documents/konstruktor/node_modules/vite/dist/node/chunks/dep-3007b26d.js:62040:24)
    at async build (file:///mnt/c/Users/aschr/Documents/konstruktor/node_modules/vite/dist/node/chunks/dep-3007b26d.js:44492:20)
    at async CAC.<anonymous> (file:///mnt/c/Users/aschr/Documents/konstruktor/node_modules/vite/dist/node/cli.js:813:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jhnnsrs** [comment]
[here](https://github.com/jhnnsrs/arkitekt-server) would be that repo

**Comment by alexschroeter** [comment]
I didn't fully understand what konstruktor is. No, need to build.
Running the Release works. Looking forward to the updated version.
